# Generated by Django 6.0 on 2026-01-30 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('technologies', models.CharField(help_text='Comma separated values', max_length=300)),
                ('experience', models.CharField(max_length=100)),
                ('positions', models.PositiveIntegerField(default=1)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
