# Generated by Django 6.0 on 2026-02-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('sales_marketing', 'Sales & Marketing'), ('customer_support', 'Customer Support'), ('tech_dev', 'Technology & Development'), ('operations_mgmt', 'Operations & Management'), ('business_dev', 'Business Development'), ('field_sales', 'Field Sales')], default='tech_dev', max_length=50),
        ),
    ]
