# Generated by Django 6.0 on 2026-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='position_applied',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('designer', 'UI/UX Designer'), ('marketing', 'Marketing Specialist')], max_length=50),
        ),
    ]
