# Generated by Django 6.0 on 2026-02-16 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_jobapplication_position_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position_applied',
            field=models.CharField(choices=[('sales_marketing', 'Sales & Marketing'), ('customer_support', 'Customer Support'), ('technology_dev', 'Technology & Development'), ('operations_mgmt', 'Operations & Management'), ('business_dev', 'Business Development'), ('field_sales', 'Field Sales')], max_length=50),
        ),
    ]
