# Generated by Django 6.0 on 2025-12-26 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('plans', '0002_remove_plan_plan_type_id_plantype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='related_plan',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='related_product',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='Leave empty = valid for all plans', related_name='coupons', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Leave empty = valid for all users', related_name='assigned_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
