# Generated by Django 6.0 on 2025-12-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bq_id', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_type_id', models.BigIntegerField(blank=True, null=True)),
                ('plan_type', models.CharField(blank=True, help_text='Plan type stored as text', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('featured_image', models.CharField(blank=True, help_text='Featured image path named by plan slug', max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('duration_type', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year'), ('mo', 'Month (mo)')], default='mo', max_length=10)),
                ('call_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('sim_type', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_value', models.CharField(blank=True, help_text='Comma-separated number of units for duration_type', max_length=255, null=True)),
                ('features', models.JSONField(blank=True, help_text='Example: [{"icon_url": "url", "text": "your text"}]', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
