# Generated by Django 6.0 on 2026-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plan_plan_type_id_plantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='plans/featured/'),
        ),
    ]
